// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RecruitX.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528222655_correction14")]
    partial class correction14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_skills_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobRequisitionId")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Mandatory")
                        .HasColumnName("skill_type");

                    b.HasKey("Id")
                        .HasName("pk_job_skills_id");

                    b.HasIndex("JobRequisitionId");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<short>("ExperienceMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("experience_months");

                    b.Property<short>("ExperienceYears")
                        .HasColumnType("smallint")
                        .HasColumnName("experience_years");

                    b.Property<int>("JobDescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("jd_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Applied")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobDescriptionId");

                    b.HasIndex("CandidateId", "JobDescriptionId");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Application_ExperienceMonths", "experience_months >= 0 AND experience_months <= 11");
                        });
                });

            modelBuilder.Entity("RecruitX.Models.ApplicationSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("application_skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("ApplicationId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("uq_application_skills_application_skill");

                    b.ToTable("application_skills", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("candidate_name");

                    b.Property<long>("ContactNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentEmployer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_employer");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("current_location_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("linkedin_url");

                    b.Property<int?>("NoticePeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("notice_period_days");

                    b.Property<int?>("PreferredLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_location_id");

                    b.Property<string>("ProposedRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposed_role");

                    b.Property<short>("RelevantExperienceMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("relevant_experience_required_months");

                    b.Property<short>("RelevantExperienceYears")
                        .HasColumnType("smallint")
                        .HasColumnName("relevant_experience_required_years");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SubSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_source");

                    b.Property<short>("TotalExperienceMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("total_experience_required_months");

                    b.Property<short>("TotalExperienceYears")
                        .HasColumnType("smallint")
                        .HasColumnName("total_experience_required_years");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PreferredLocationId");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCountry")
                        .HasColumnType("text")
                        .HasColumnName("client_country");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("RecruitX.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JobDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("FilledPositions")
                        .HasColumnType("integer")
                        .HasColumnName("fill_positions");

                    b.Property<string>("JobDesc")
                        .HasColumnType("text")
                        .HasColumnName("job_desc");

                    b.Property<int>("JobRequisitionId")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.Property<int?>("JobRequisitionId1")
                        .HasColumnType("integer");

                    b.Property<string>("Updates")
                        .HasColumnType("text")
                        .HasColumnName("updates");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobRequisitionId");

                    b.HasIndex("JobRequisitionId1");

                    b.ToTable("job_descriptions", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JobRequisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedOnboardingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedSalaryRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("HasClientInterview")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOnsiteOpportunity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("HiringManager")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IdealStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsBillable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDuties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobSpecification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("NumPositions")
                        .HasColumnType("integer");

                    b.Property<int?>("OnSiteDetailId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RelevantExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("RelevantExperienceYears")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<int?>("TotalExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("WorkModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HiringManager");

                    b.HasIndex("LocationId");

                    b.HasIndex("OnSiteDetailId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("job_requisitions", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JrAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to");

                    b.Property<int>("JobRequisitionId")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("JobRequisitionId");

                    b.ToTable("jr_assignments", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.OnSiteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("onsite_detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientBackground")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_background");

                    b.Property<string>("ClientLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractDuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_duration");

                    b.Property<string>("ContractType")
                        .HasColumnType("text")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("IdealStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ideal_start_date");

                    b.Property<string>("InterviewProcess")
                        .HasColumnType("text")
                        .HasColumnName("interview_process");

                    b.Property<bool?>("IsH1TransferAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("h1_transfer_accepted");

                    b.Property<bool?>("IsTravelRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("travel_required");

                    b.Property<int>("JrId")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.Property<string>("PreferredTimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_time_zone");

                    b.Property<string>("PreferredVisaStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_visa_status");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rate");

                    b.Property<string>("ReportingTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporting_to");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JrId")
                        .IsUnique();

                    b.ToTable("on_site_details", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobskills_jr_id");

                    b.HasOne("RecruitX.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobskills_skill_id");

                    b.Navigation("JobRequisition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitX.Models.Application", b =>
                {
                    b.HasOne("RecruitX.Models.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_candidate_id");

                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_applications_created_by");

                    b.HasOne("RecruitX.Models.JobDescription", "JobDescription")
                        .WithMany("Applications")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_jd_id");

                    b.Navigation("Candidate");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("RecruitX.Models.ApplicationSkill", b =>
                {
                    b.HasOne("RecruitX.Models.Application", "Application")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_skills_application_id");

                    b.HasOne("RecruitX.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_skills_skill_id");

                    b.Navigation("Application");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitX.Models.Candidate", b =>
                {
                    b.HasOne("RecruitX.Models.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Location", "PreferredLocation")
                        .WithMany()
                        .HasForeignKey("PreferredLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLocation");

                    b.Navigation("PreferredLocation");
                });

            modelBuilder.Entity("RecruitX.Models.Employee", b =>
                {
                    b.HasOne("RecruitX.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_department_id");

                    b.HasOne("RecruitX.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RecruitX.Models.JobDescription", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.JobRequisition", null)
                        .WithMany()
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisitionId1");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("RecruitX.Models.JobRequisition", b =>
                {
                    b.HasOne("RecruitX.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Employee", "HiringManagerEmployee")
                        .WithMany()
                        .HasForeignKey("HiringManager")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.OnSiteDetail", "OnSiteDetail")
                        .WithMany()
                        .HasForeignKey("OnSiteDetailId");

                    b.HasOne("RecruitX.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HiringManagerEmployee");

                    b.Navigation("Location");

                    b.Navigation("OnSiteDetail");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("RecruitX.Models.JrAssignment", b =>
                {
                    b.HasOne("User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("RecruitX.Models.OnSiteDetail", b =>
                {
                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithOne()
                        .HasForeignKey("RecruitX.Models.OnSiteDetail", "JrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OnsiteJobDetail_JobRequisition");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("RecruitX.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RecruitX.Models.Application", b =>
                {
                    b.Navigation("ApplicationSkills");
                });

            modelBuilder.Entity("RecruitX.Models.Candidate", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RecruitX.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RecruitX.Models.Employee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitX.Models.JobDescription", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("RecruitX.Models.JobRequisition", b =>
                {
                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
